import SideBar from './sideBar/page'
import { Nunito } from 'next/font/google'

const nunito = Nunito({ 
  subsets: ['latin'],
  style:['normal'] 
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DashLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.className} flex w-screen h-screen`}>
        <SideBar/>
        {children}  
      </body>
    </html>
  )
}
