import { Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
	subsets: ["latin"],
	style: ["normal"],
});

export const metadata = {
	title: "SIGA Software - INÍCIO",
	description: "Generated by create next app",
	favicon: require("./favicon.ico"),
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${nunito.className} flex w-screen h-screen`}>
				{/* <SideBar/> */}
				{children}
			</body>
		</html>
	);
}
